Bug#37458343 Fix warnings from PGO/LTO build [innodb,noclose]
When building with LTO at the -fprofile-use phase, we get extra warnings.
Fix them, or silence them, or downgrade from error to warning.

This patch was developed on el9 using gcc 13.3.1

Sample warnings fixed:
storage/innobase/page/page0zip.cc:2680:9:
/usr/include/bits/string_fortified.h:29:33: error: memcpy accessing 18446744073709551522 bytes at offsets 94 and 94 overlaps 9223372036854775621 bytes at offset -9223372036854775715 [-Werror=restrict]

storage/innobase/page/page0zip.cc:2680:9:
/usr/include/bits/string_fortified.h:29:33: error: memcpy pointer overflow between offset 94 and size 184467440737095

storage/innobase/page/page0zip.cc:2680:9:
/usr/include/bits/string_fortified.h:29:33: error: memcpy specified bound 18446744073709551522 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]

storage/innobase/lock/lock0lock.cc:6275:35:
innobase/include/detail/ut/allocator_traits.h:72:56: error: argument 1 value ‘9223372036854775832’ exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]

Change-Id: I6bde2ab57acb559c2f8ab324a9a6e527015fd825
(cherry picked from commit 8765e4bce331ef9c664af1b098bb5df143b8a4a3)