Bug#37802388 CREATE TABLESPACE fails with wrong error: 723 'No such table existed' when logfile group does not exist
Problem:
When we create a tablespace, if the specified
logfile group does not exist, operation fails with
error: 723 'No such table existed'
This is confusing since, from the user perspective,
what is missing is a LOGFILE not a table.

Solution:
Remap error 723 to 789 'Logfile group not found' when
CREATE TABLESPACE fails due to a missing LOGFILE GROUP

Change-Id: Ic48b07160109422a8e7f07b5afe26661b38f2045