Bug#37458343 Fix warnings from PGO/LTO build [xplugin,noclose]
When building with LTO at the -fprofile-use phase, we get extra warnings.
Fix them, or silence them, or downgrade from error to warning.

This patch was developed on el9 using gcc 13.3.1

error: enum_value may be used uninitialized [-Werror=maybe-uninitialized]
translation_validator.h:164
164 |       Translate_to_type enum_value;

Change-Id: I899f0b599422ec693cc5e9de1bf474899e10e3a8
(cherry picked from commit 509ed320c6e7d66d4d6b269d23fac2d414916774)