Bug#36528480 pointer stream_31(D) may be used after fclose
Seen during PGO/LTO build on el9

error: pointer 'stream_31(D)' may be used after
'fclose' [-Werror=use-after-free]
 190 |  err = mysys_priv::RetryOnEintr([&]() { return fclose(stream); }, -1);

man fclose(3) says

In either case, any further access (including another call to
fclose()) to the stream results in undefined behavior.

So do not try to fclose a stream more than once.

Change-Id: I1c640bf70ebbe2154042ee91fa993c02f500aadf
(cherry picked from commit bf747be6bfe9b1329cdb4fe00f4b8e1e84eb80e0)